server:
  port: 8080
  servlet-path: /JPA #servlet映射路径模式，对应日志中打印的：Mapping servlet: 'dispatcherServlet' to [/JPA/*]
  context-path: /SpringBoot #应用程序上下文（一般为项目名称）

spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest
        username: root
        password: root
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    jpa:
        hibernate:
                  #配置自动建表：updata:没有表新建，有表更新操作
                  ddl-auto: update
        #控制台显示建表语句
        show-sql: true

logging:
      level:
            com:
                magic:
                      springboot: DEBUG


######################
#start
#仅供使用mybatis官方提供的Spring Boot整合包实现时使用
#spring:
#    datasource:
#        name: test
#        url: jdbc:mysql://127.0.0.1:3306/mytest
#        username: root
#        password: root
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20

#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.magic.spingboot.model

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

#end
#######################